blank_issues_enabled: false
contact_links:
   - name: Question
     url: https://discord.com/invite/3TPgAjDF
     about: Usage questions and support requests are answered in the MuryP Discord. Specific channel muryp-gh.